##################################
#ollama pull qwen2.5-coder:7b
#ollama pull qwen2.5-coder:1.5b
#ollama pull nomic-embed-text
##################################
name: Local Pirate Config
version: 1.0.0
schema: v1
models:
  - name: Main
    provider: ollama
    model: qwen2.5-coder:7b
   
    roles:
      - chat
  
  - name: Edit
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - edit

  - name: Apply
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - apply
  
  - name: Fast Autocomplete
    provider: ollama
    model: qwen2.5-coder:1.5b
    roles:
      - autocomplete

  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed


rules:
  - Give concise responses
  - Always assume TypeScript rather than JavaScript
  - Talk like a pirate
  - Do not output markdown